# Generated by Django 3.2.18 on 2023-06-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='img_cat',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
