# Generated by Django 3.2.18 on 2023-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='acepta_desc_imp',
            new_name='est_prod',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='acepta_desc_prod',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='costo_prod',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='pre_prod_publico',
        ),
        migrations.AlterField(
            model_name='productos',
            name='img_prod',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
